### ISSUE TITLE
How do I override php_executable?

### ISSUE THREAD

**Issue by alexciarlillo** [geerlingguy/ansible-role-composer#39]
Sorry for my ignorance, but I have tried to override this variable in a half-dozen different places and it is not working.

Here is my composer task (roles/deploy/tasks/build.yml)
```
- name: Install Composer dependencies
  composer:
    no_scripts: yes
    working_dir: "{{ deploy_helper.new_release_path }}"
  become: true
```
I have tried setting the variable in roles/deploy/vars/main.yml, roles/deploy/defaults/main.yml, group_vars/staging/main.yml, group_vars/all/main.yml, and all created a task to set_fact immediately before the above task. None of these seem to override the default of 'php'. I am definitely fairly new to ansible, but after reading and re-reading the variables documentation I have to believe setting it one of those places should have worked?
