### ISSUE TITLE
Composer command plugin?

### ISSUE THREAD

**Issue by mglaman** [geerlingguy/ansible-role-composer#55]
If I wanted to run any Composer commands as a task, I'd have to use the shell module.

Here's an example I was considering -- for adding a repository URL and requiring it.

```
- name: Add private repo URL to global
  composer:
    command: config
    arguments: repositories.drupal composer https://packagist.drupal-composer.org
    global: true
- name: Add project to global
   composer:
     command: require
     arguments: drupal/coder
     global: true
```

That's a little rough, but the concepts are there. Not sure if viable
