### ISSUE TITLE
composer_global_packages hangs after each package operation

### ISSUE THREAD

**Issue by Bilge** [geerlingguy/ansible-role-composer#56]
Specifying `composer_global_packages` causes Ansible to hang after each package, even though package installation succeeds. If *N* global packages are specified, Ansible has to be re-run *N* times to complete the task.

### Example

```yml
- name: Composer
  import_role: name=geerlingguy.composer
  vars:
    composer_home_path: /home/bilge/.composer
    composer_home_owner: bilge
    composer_home_group: bilge
    composer_global_packages:
      - { name: hirak/prestissimo }
      - { name: d11wtq/boris }
  tags: composer
```
