### ISSUE TITLE
Failed to set permissions on the temporary files Ansible needs to create when becoming an unprivileged user

### ISSUE THREAD

**Issue by piotrkochan** [geerlingguy/ansible-role-composer#69]
Vars:
```
application_user: test_user
composer_home_path: '~/.composer'
composer_home_owner: test_user
composer_home_group: test_user
composer_global_packages:
 - { name: gordalina/cachetool }
```

Playbook:
```
---
- name: Add application user - {{application_user}}
  user: name={{application_user}} groups=www-data state=present
- name: Install Composer
  import_role:
    name: geerlingguy.composer

```

```
TASK [geerlingguy.composer : Install configured globally-required packages.] *****************************************************************************************************************************************************
fatal: [kochan_vm_20_3c]: FAILED! => {"msg": "Failed to set permissions on the temporary files Ansible needs to create when becoming an unprivileged user (rc: 1, err: chown: changing ownership of '/var/tmp/ansible-tmp-1600936221.55-31066-138531225095947/': Operation not permitted\nchown: changing ownership of '/var/tmp/ansible-tmp-1600936221.55-31066-138531225095947/AnsiballZ_command.py': Operation not permitted\n}). For information on working around this, see https://docs.ansible.com/ansible/become.html#becoming-an-unprivileged-user"}
```

```ansible --version
ansible 2.9.12
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/kochan/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.18rc1 (default, Apr  7 2020, 12:05:55) [GCC 9.3.0]
```
